#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
# app/config/routing.yml
logout:
    path: /logout
    defaults: { _controller: AppBundle:Default:logout }

setZone:
    path: /zone
    defaults: { _controller: AppBundle:Default:setZone }

inquiryHandler:
    path: /dashboard/inquiryHandler
    defaults: { _controller: AppBundle:Default:inquiryHandler }

dashboard:
    path: /dashboard
    defaults: { _controller: AppBundle:Default:dashboard }

fail:
    path: /fail
    defaults: { _controller: AppBundle:Default:fail }

homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

overview:
    path: /dashboard/overview
    defaults: { _controller: AppBundle:Default:overview }

home_error:
    path: /error/{error_name}
    defaults: { _controller: AppBundle:Default:homeError }

client_summary:
    path: dashboard/client/summary
    defaults: { _controller: AppBundle:Client:summary }

client_requests:
    path: dashboard/client/requests
    defaults: { _controller: AppBundle:Client:requests }

client_usage:
    path: dashboard/client/usage
    defaults: { _controller: AppBundle:Client:usage }

client_packages:
    path: dashboard/client/packages
    defaults: { _controller: AppBundle:Client:packages }

client_settings:
    path: dashboard/client/settings
    defaults: { _controller: AppBundle:Client:settings }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profilelogin/check-google

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"


hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"


facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google