usage_type_index:
    path:     /
    defaults: { _controller: "AppBundle:usage_type:index" }
    methods:  GET

usage_type_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:usage_type:show" }
    methods:  GET

usage_type_new:
    path:     /new
    defaults: { _controller: "AppBundle:usage_type:new" }
    methods:  [GET, POST]

usage_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:usage_type:edit" }
    methods:  [GET, POST]

usage_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:usage_type:delete" }
    methods:  DELETE
